config/routes.rb
Rails.application.routes.draw do

  root "users#home"
  get "/" => "users#home"
  get "/home/about" => "users#about"


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only:[:show, :edit, :update, :index]

  resources :books, only:[:index, :show, :new, :create, :edit, :update, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, length: { in: 2..20 }, presence: true
  validates :introduction, length: {maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_in_path_for(resource)
  		user_path(resource)
    end

	before_action :configure_permitted_parameters, if: :devise_controller?
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end

  protected
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  protected
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	def authenticate
		redirect_to home_url unless user_signed_in?
	end

	before_action :ensure_correct_user, {only:[:edit, :update]}
    def ensure_correct_user
    	@book = Book.find(params[:id])
    	if current_user.id != @book.user_id
       		redirect_to books_path
    	end
  end

	def index
		@user = User.find(current_user.id)

		@book_new = Book.new
		@books = Book.all
	end

	def show
		@book = Book.find(params[:id])
		@user = User.find(@book.user_id)

	    @book_new = Book.new
	end

	def new
		@book_new = Book.new
	end

	def create
		@book_new = Book.new(book_params)
		@book_new.user_id = current_user.id
		if @book_new.save
			flash[:notice] = "You have creatad book successfully."
			redirect_to book_path(@book_new)
		else
			@user = User.find(current_user.id)
			@books = Book.all
			render("books/index")
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "You have updated book successfully."
			redirect_to book_path(@book)
		else
    		render("books/edit")
    	end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:index, :show, :edit]
  def authenticate
    redirect_to home_url unless user_signed_in?
  end

  before_action :ensure_correct_user, {only:[:edit, :update]}
  def ensure_correct_user
    if current_user.id != params[:id].to_i
       redirect_to user_path(current_user)
    end
  end


  def home
  end

  def about
  end

  def index
    @user = User.find(current_user.id)
    @users = User.all
    @book_new = Book.new
  end

  def show
  	@user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books
  end

  def  edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
    else
       render ("users/edit")
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div ckass="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>

			 <% if @book.errors.any? %>
                <h2> <%= @book.errors.count %>error prohibited this obj from being saved</h2>
                 <ul>
                  <% @book.errors.full_messages.each do |message| %>
                   <li> <%= message %> </li>
                  <% end %>
                 </ul>
             <% end %>

			 <div class="field">
			 	<%= f.label :title %> <br>
			 	<%= f.text_field :title %>
			 </div>
			 <div class="field">
			 	<%= f.label :opinion %> <br>
			 	<%= f.text_area :body %>
			 </div>
			 <div class="field">
			 	<%= f.submit "Update Book" %>
			 </div>
			<% end %>
			<%= link_to "Show", book_path(@book) %> |
			<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">

 <%= render 'users/list_user', { user: @user, book_new: @book_new } %>

	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table">
			<tr>
				<td></td>
				<td>Title</td>
				<td>Opinion</td>
				<td></td>
			</tr>
			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user) do %>
					<%= attachment_image_tag book.user, :profile_image, size:"50x50",
					format:"jpeg", fallback:"no_image.jpg" %>
				    <% end %></td>
				<td>
					<%= link_to book_path(book) do %>
					<%= book.title %> </td>
					<% end %>
				<td> <%= book.body %> </td>
			</tr>
			<% end %>
		</table>
	</div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">

 <%= render 'users/list_user', { user: @user, book_new: @book_new } %>

	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
			<tr>
				<td>
					<%= link_to user_path(@user) do %>
					<%= attachment_image_tag @user, :profile_image, size:"50x50",
					format:"jpeg", fallback:"no_image.jpg" %>
					<br> <%= @user.name %>
				    <% end %></td>
				<td>
					<%= link_to book_path(@book) do %>
					<%= @book.title %> </td>
					<% end %>
				<td> <%= @book.body %> </td>
				<% if current_user.id == @user.id %>
				<td> <%= link_to "Edit", edit_book_path(@book) ,
					class:"btn btn-default btn-sm" %> </td>
				<td> <%= link_to "Destroy", book_path(@book), method: :delete ,
					class:"btn btn-default btn-sm" %> </td>
				<% end %>
			</tr>
		</table>
	</div>

 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-default ">
    <div class="container">
      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
    <nav>
    <ul class="nav navbar-right nav-pills" >
    <% if user_signed_in? %>
      <li class="">
        <%= link_to 'Home', user_path(current_user) %>
      </li>
      <li class="">
        <%= link_to "Users", "/users" %>
      </li>
      <li class="">
        <%= link_to 'Books', "/books" %>
      </li>
      <li class="">
        <%= link_to "logout", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li class="">
        <%= link_to "/" do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true">Home</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to "/home/about" do %>
         <span class="glyphicon glyphicon-link" aria-hidden="true">About</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_registration_path do %>
         <span class="glyphicon glyphicon-edit" aria-hidden="true">sign up</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_session_path do %>
         <span class="glyphicon glyphicon-log-in" aria-hidden="true">login</span>
         <% end %>
      </li>
    <% end %>
  </ul>
  </nav>

   </div>
  </header>
  <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
    <%= yield %>
  </body>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/users/_list.html.erb
<div class="container">
 <div class="row">

	<div class="col-xs-3">
		<h2>User info</h2>
		<%= attachment_image_tag user, :profile_image, size:"100x100", format:"jpeg",
			fallback:"no_image.jpg" %>
		<table class="table">
			<tr>
				<td>name</td>
				<td> <%= user.name %> </td>
			</tr>
			<tr>
				<td>introduction</td>
				<td> <%= user.introduction %> </td>
			</tr>
		</table>
		<%= link_to "編集", edit_user_path(user) %>
	</div>

	<div class="col-xs-9">
		<h2> <%= title %> </h2>
		<table class="table">
			<tr>
				<td>image</td>
				<td>name</td>
				<td></td>
			</tr>
			<% users.each do |user| %>
			<tr>
				<td> <%= attachment_image_tag user, :profile_image, size:"50x50",
					format:"jpeg", fallback:"no_image.jpg" %> </td>
				<td> <%= user.name %> </td>
				<td> <%= link_to "show", user_path(user) %> </td>
			</tr>
			<% end %>
		</table>
	</div>

 </div>
</div>

app/views/users/_list_user.html.erb
<% if @book_new.errors.any? %>
 <h2> <%= @book_new.errors.count %>error prohibited this obj from being saved</h2>
 <ul>
  <% @book_new.errors.full_messages.each do |message| %>
   <li> <%= message %> </li>
   <% end %>
  </ul>
<% end %>

<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, size:"100x100", format:"jpeg",
		fallback:"no_image.jpg" %>
	<table class="table">
		<tr>
			<td>name</td>
			<td> <%= user.name %> </td>
		</tr>
		<tr>
			<td>introduction</td>
			<td> <%= user.introduction %> </td>
		</tr>
	</table>
	<%= link_to edit_user_path(user) do %>
		<span class="glyphicon glyphicon-wrench btn btn-default block-btn"
			aria-hidden="true"></span>
	<% end %>

	<h2>New book</h2>
		<%= form_for(book_new) do |f| %>
		 <div class="field">
		  <%= f.label :title %> <br>
		  <%= f.text_field :title, autofocus: true %>
		 </div>
		<div class="field">
		 	<%= f.label :opinion %> <br>
		 	<%= f.text_area :body, autofocus: true %>
		</div>
		<div class="field">
  		  <%= f.submit "Create Book" ,class:"btn btn-default" %>
  		</div>
		<% end %>
</div>

app/views/users/about.html.erb
<div class="container">
			<h1>Welcome to
				<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers !!</h1>
</div>

app/views/users/edit.html.erb
<div class="container">
<h2>User info</h2>
      <% if @user.errors.any? %>
             <h2> <%= @user.errors.count %>error prohibited this obj from being saved</h2>
             <ul>
              <% @user.errors.full_messages.each do |message| %>
               <li> <%= message %> </li>
               <% end %>
              </ul>
            <% end %>

<%= form_for (@user) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
  <%= f.label :image %>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画面" %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
  </div>


  <div class="field">
  <%= f.submit "Update User" %>
  </div>
<% end %>

</div>

app/views/users/home.html.erb
<div class="container">

	<div id="container">
	<div id="theTarget">
		<div class="image1"></div>
		<div class="image2"></div>
		<div class="image3"></div>
		<div class="image4"></div>
		<div class="image5"></div>
	</div>
	</div>

	<div class="row">
		<div class="col-md-offset-3 col-md-6">
			<h1>Welcome to
				<span class="glyphicon glyphicon-book" aria-hidden="true"></span>
			Bookers !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span>Bookers</p>
			<p>you can share and exchange  your opinions , inpressions , and emotions</p>
			<p>about various books!</p>

			<%= link_to "Log in", new_user_session_path ,class:"btn btn-default block-btn" %>
			<%= link_to "Sign up", new_user_registration_path ,class:"btn btn-default    block-btn" %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">

 <%= render 'users/list_user', { user: @user, book_new: @book_new } %>

	<div class="col-xs-9">
		<h2>Users</h2>
		<table class="table">
			<tr>
				<td>image</td>
				<td>name</td>
				<td></td>
			</tr>
			<% @users.each do |user| %>
			<tr>
				<td> <%= attachment_image_tag user, :profile_image, size:"50x50",
					format:"jpeg", fallback:"no_image.jpg" %> </td>
				<td> <%= user.name %> </td>
				<td> <%= link_to "Show", user_path(user) %> </td>
			</tr>
			<% end %>
		</table>
	</div>

 </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">

 <%= render 'users/list_user', { user: @user, book_new: @book_new } %>

	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table">
			<tr>
				<td></td>
				<td>title</td>
				<td>opinion</td>
			</tr>
			<% @books.each do |book| %>
			<tr>
				<td> <%= link_to user_path(book.user_id) do %>
					<%= attachment_image_tag @user, :profile_image, size:"50x50",
					format:"jpeg", fallback:"no_image.jpg" %> <% end %> </td>
				<td> <%= link_to book_path(book) do %>
					<%= book.title %> <% end %></td>
				<td> <%= book.body %></td>
			</tr>
			<% end %>
		</table>
	</div>
 </div>
</div>